### ISSUE TITLE
SBCL in Ubuntu 15.04

### ISSUE THREAD

**Issue by humbhenri** [AccelerationNet/css-selectors#15]
Doesn't work in Ubuntu 15.04 (SBCL 1.2.4.debian)
 READ error during COMPILE-FILE:
;   
;     unrecognized character name: "u+00A0"
;   
;       Line: 7, Column: 12, File-Position: 172
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /home/humberto/quicklisp/local-projects/css-selectors/src/parse.lisp"

**Comment by bgraf** [comment]
Reproduced the error. Does not happen with SBCL 1.3.0.debian from [launchpad](https://launchpad.net/ubuntu/+source/sbcl).

**Comment by html** [comment]
Reproduced on SBCL 1.1.14.debian

**Comment by bobbysmith007** [comment]
Sorry I think that I had missed this... let me check whats going on

**Comment by bobbysmith007** [comment]
I think that this should be fixed now... sorry for the troubles
